#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# OBSCURA installer — sets up the `obscura` command and the systemd service so
# the toolkit can be driven with `sudo systemctl start obscura`.
#
#   sudo ./deploy/install.sh                 # install to /opt/obscura
#   sudo INSTALL_DIR=/srv/obscura ./deploy/install.sh
#
# What it does:
#   1. Copies the project to $INSTALL_DIR (default /opt/obscura).
#   2. Installs an `obscura` launcher to /usr/local/bin.
#   3. Installs + enables the systemd unit (WorkingDirectory pinned to it).
#
# Requirements: Docker + the compose plugin (the service runs the container).
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/obscura}"
BIN_PATH="/usr/local/bin/obscura"
UNIT_PATH="/etc/systemd/system/obscura.service"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root (sudo)." >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is required but not found. Install Docker first." >&2
  exit 1
fi

echo "==> Installing OBSCURA from ${SRC_DIR} to ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"
# Copy the project, excluding local cruft and secrets. .env is intentionally not
# copied — create ${INSTALL_DIR}/.env from .env.example after install if needed.
rsync -a --delete \
  --exclude '.git' --exclude '.venv' --exclude '__pycache__' \
  --exclude '*.pyc' --exclude '.pytest_cache' --exclude '.ruff_cache' \
  --exclude '.env' --exclude 'logs' \
  "${SRC_DIR}/" "${INSTALL_DIR}/"
mkdir -p "${INSTALL_DIR}/logs"

echo "==> Installing launcher to ${BIN_PATH}"
cat > "${BIN_PATH}" <<EOF
#!/bin/sh
# OBSCURA launcher (generated by deploy/install.sh)
exec python3 "${INSTALL_DIR}/cli.py" "\$@"
EOF
chmod +x "${BIN_PATH}"

echo "==> Installing systemd unit to ${UNIT_PATH}"
sed "s#^WorkingDirectory=.*#WorkingDirectory=${INSTALL_DIR}#" \
  "${INSTALL_DIR}/deploy/obscura.service" > "${UNIT_PATH}"

systemctl daemon-reload
systemctl enable obscura >/dev/null 2>&1 || true

cat <<EOF

✔ OBSCURA installed.

  Start now:      sudo systemctl start obscura
  Start on boot:  sudo systemctl enable obscura   (already enabled)
  Status:         sudo systemctl status obscura
  Logs:           obscura logs --docker -f   (or: journalctl -u obscura -f)
  Stop:           sudo systemctl stop obscura

  CLI is on PATH:  obscura version | obscura doctor | obscura status --docker

  Optional: add LLM keys at ${INSTALL_DIR}/.env (copy from .env.example),
  or enter them live in the UI Configuration panel.

  UI: http://127.0.0.1:8501
EOF
